---

- name: check /etc/init.d/iptables
  stat:
    path: /etc/init.d/iptables
  register: check_etc_iptables

- name: check /usr/libexec/iptables/iptables.init
  stat:
    path: /usr/libexec/iptables/iptables.init
  register: check_usr_iptables

- name: set dashboard ports to iptables
  iptables:
    chain: INPUT
    action: insert
    protocol: tcp
    destination_port: "{{ dashboard_port + item|int }}"
    jump: ACCEPT
  with_sequence: >
    start=0
    count={{ spare_count + 1 }}
  notify: save iptables
