---

- name: include tasks Redhat.yml
  include_tasks: Redhat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int > 6

- name: include tasks Ubuntu.yml
  include_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 14
