---

- name: include main tasks
  include_tasks: '{{ task_item }}'
  loop_control:
    loop_var: task_item
  with_first_found:
    - files:
      - '{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_os_family }}-{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_os_family }}.yml'
      - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_distribution }}.yml'
      skip: false
