---

- name: include tasks agent.yml
  include_tasks: agent.yml

- name: include tasks service.yml
  include_tasks: service.yml

- name: service iptables status
  shell: service iptables status
  args:
    warn: False
  register: iptables_status
  changed_when: False
  failed_when: iptables_status.rc not in [ 0, 3 ]

- name: include tasks iptables.yml
  include_tasks: iptables.yml
  when: iptables_status.rc == 0
